<?php

// Global Compliance
global $_COMPLIANCE;

// IDX Compliance Settings
$_COMPLIANCE = array();

// Search Result Limit
$_COMPLIANCE['limit'] = 500;

// Display Update Time
$_COMPLIANCE['update_time'] = true;

// Disclaimer Text
$_COMPLIANCE['disclaimer'] = array('');

if (in_array($_GET['load_page'], array('', 'search', 'search_map', 'details', 'map', 'streetview', 'birdseye', 'directions', 'local', 'brochure', 'sitemap', 'search_form','dashboard'))) {

    // Disclaimer
    $_COMPLIANCE['disclaimer'][] = '<p class="disclaimer">The data relating to real estate on this web site comes in part from the MLS&reg; Reciprocity program of the Real Estate Board of Greater Vancouver or the Fraser Valley Real Estate Board. Real estate listings held by participating real estate firms are marked with the MLS&reg; logo and detailed information about the listing includes the name of the listing agent. This representation is based in whole or part on data generated by the Real Estate Board of Greater Vancouver or the Fraser Valley Real Estate Board which assumes no responsibility for its accuracy. The materials contained on this page may not be reproduced without the express written consent of the Real Estate Board of Greater Vancouver or the Fraser Valley Real Estate Board. </p>';

    // Details Logo
    $_COMPLIANCE['disclaimer'][] = '<p class="disclaimer"><img alt="Real Estate Board of Greater Vancouver Logo" src="' . Settings::getInstance()->SETTINGS['URL_IMG'] . 'logos/mlsrlogo.gif" /></p>';

}

// Search Results, Display Thumbnail Icon
$_COMPLIANCE['results']['show_icon'] = '<img alt="Real Estate Board of Greater Vancouver Logo" src="' . Settings::getInstance()->SETTINGS['URL_IMG'] . 'logos/mlsrlogosmall.png" border="0" align="center" />';

// Search Results, Display MLS Number
$_COMPLIANCE['results']['show_mls'] = true;

// Search Results, Display Office Name
$_COMPLIANCE['results']['show_office'] = true;

if (in_array($_GET['load_page'], array('details', 'brochure'))) {

	// Listing Details, Display Office Name
	$_COMPLIANCE['details']['show_office'] = true;

}

// Brochure logo
$_COMPLIANCE['logo'] = Settings::getInstance()->SETTINGS['URL_IMG'] . 'logos/mlsrlogo.gif';
// Width (FPDF, not actual)
$_COMPLIANCE['logo_width'] = 20;
// Paragraph key
$_COMPLIANCE['logo_location'] = 1;

$_COMPLIANCE['strip_words']['meta_description'] = array('realtors', 'realtor', 'mls®', 'mls', 'multiple listings service');
