import REWMap from '../../../../js/map/Map';
import '../../../../js/map/Map.Marker';
import '../../../../js/map/Map.Tooltip';
import '../../../../js/map/Map.Directions';
import '../../../../js/map/Map.Streetview';
import '../../../../js/map/Map.MarkerLabel';
import '../../../../js/map/Map.MarkerManager';
import '../../../../js/map/Map.MarkerCluster';
import '../../../../js/map/Map.SearchControl';
import '../../../../js/map/Map.RadiusControl';
import '../../../../js/map/Map.PolygonControl';
export default REWMap;