image: rewdocker/rew-framework-build:rewcrm@sha256:c36a83e59a80fca4694acb35068a5fd2f91142cdb8c50eccbc88fa77fcd704bd

before_script:
# Run ssh-agent (inside the build environment)
- eval $(ssh-agent -s)

# Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
- ssh-add <(echo "$SSH_PRIVATE_KEY")

# For Docker builds disable host key checking. Be aware that by adding that
# you are suspectible to man-in-the-middle attacks.
# WARNING: Use this only with the Docker executor, if you use it with shell
# you will overwrite your user's SSH config.
- mkdir -p ~/.ssh
- '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - install
  - post install
  - deploy
  - smoke test

####### INSTALL STAGE #######
php:
  stage: install
  only:
    - dev
    - uat
    - UAT
  tags:
    - 'gke'
  script:
    - build beta --config=4.8-elite --build-steps=copy:environment,copy:change-root,composer:install

php - cenext:
  stage: install
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_vendor_cenext"
    paths:
      - vendor
    expire_in: 1 day
  tags:
    - 'gke'
  script:
    - build beta --config=4.8-cenext --build-steps=copy:environment,copy:change-root,composer:install

node - base:
  stage: install
  only:
    - dev
    - uat
    - UAT
  tags:
    - 'gke'
  script:
    - build beta --config=4.8-cenext --node.working-path=. --build-steps=copy:environment,node:install --node.manager=npm

node - crm:
  stage: install
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_node_crm"
    paths:
      - httpdocs/backend/node_modules
    expire_in: 1 day
  tags:
    - 'gke'
  script:
    - build beta --config=4.8-cenext --node.working-path=httpdocs/backend --build-steps=copy:environment,copy:change-root,node:install --node.manager=npm

node - elite:
  stage: install
  only:
    - dev
    - uat
    - UAT
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_node_elite"
    paths:
      - httpdocs/inc/skins/elite/node_modules
    expire_in: 1 day
  tags:
    - 'gke'
  script:
    - build beta --config=4.8-elite --node.working-path=httpdocs/inc/skins/elite --build-steps=copy:environment,copy:change-root,node:install --node.manager=npm

node - cenext:
  stage: install
  only:
    - dev
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_node_cenext"
    paths:
      - httpdocs/inc/skins/ce/node_modules
    expire_in: 1 day
  tags:
    - 'gke'
  script:
    - build beta --config=4.8-cenext --node.working-path=httpdocs/inc/skins/ce --build-steps=copy:environment,copy:change-root,node:install --node.manager=npm

####### POST INSTALL STAGE #######
build crm assets:
  stage: post install
  only:
    - dev
    - uat
    - UAT
  dependencies:
    - :node - crm
  tags:
    - 'gke'
  script:
    - build beta --config=4.8-cenext --node.working-path=httpdocs/backend --build-steps=copy:environment,copy:change-root,node:install,node:run --node.manager=npm

lint crm assets:
  stage: post install
  except:
    - dev
    - uat
    - UAT
  dependencies:
    - :node - crm
  tags:
    - 'gke'
  script:
    - build beta --config=4.8-cenext --node.working-path=httpdocs/backend --build-steps=copy:environment,copy:change-root,node:install,node:run --node.scripts.httpdocs/backend=eslint,stylelint --node.manager=npm

build elite assets:
  stage: post install
  only:
    - dev
    - uat
    - UAT
  dependencies:
    - :php
    - :node - elite
  tags:
    - 'gke'
  script:
    - build beta --config=4.8-elite --node.working-path=httpdocs/inc/skins/elite --build-steps=copy:environment,copy:change-root,node:install --node.scripts.httpdocs/inc/skins/elite=dev --node.manager=npm

unit test:
  stage: post install
  dependencies:
    - :php
  tags:
    - 'gke'
  script:
    - unit beta --config=4.8-elite

####### DEPLOY STAGE #######
deploy cenext:
  stage: deploy
  environment:
    name: cenext
    url: http://dev.48-beta-cenext.rewdev.com/backend
  when: manual
  dependencies:
    - :php - cenext
    - :node - base
    - :node - cenext
    - :build crm assets
  tags:
    - 'gke'
  script:
    - deploy beta --config=4.8-cenext --node.manager=npm

deploy bcse:
  stage: deploy
  environment:
    name: bcse
    url: http://dev.48-beta-bcse.rewdev.com
  when: manual
  dependencies:
    - :php
    - :node - base
    - :build crm assets
  tags:
    - 'gke'
  script:
    - deploy beta --config=4.8-bcse --node.manager=npm

deploy elite:
  stage: deploy
  environment:
    name: elite
    url: http://dev.48-beta-elite.rewdev.com
  only:
    - dev
  dependencies:
    - :php
    - :node - base
    - :build crm assets
    - :build elite assets
  tags:
    - 'gke'
  script:
    - deploy beta --config=4.8-elite --node.manager=npm

deploy fese:
  stage: deploy
  environment:
    name: fese
    url: http://dev.48-beta-fese.rewdev.com
  when: manual
  dependencies:
    - :php
    - :node - base
    - :build crm assets
  tags:
    - 'gke'
  script:
    - deploy beta --config=4.8-fese --node.manager=npm

deploy lec2015:
  stage: deploy
  environment:
      name: lec2015
      url: http://dev.48-beta-lec2015.rewdev.com/backend
  when: manual
  dependencies:
    - :php
    - :node - base
    - :build crm assets
  tags:
    - 'gke'
  script:
    - deploy beta --config=4.8-lec2015 --node.manager=npm

deploy stage:
  stage: deploy
  environment:
    name: stage
    url: http://dev.48-uat.rewdev.com
  only:
  - uat
  - UAT
  tags:
    - 'gke'
  script:
    - deploy uat --config=4.8-uat --node.manager=npm

deploy qa:
  stage: deploy
  environment:
    name: qa
    url: http://dev.cenext-qa.rewdev.com
  when: manual
  dependencies:
    - :php - cenext
    - :node - base
    - :node - cenext
    - :build crm assets
  tags:
    - 'gke'
  script:
    - deploy qa --config=4.8-cenext --node.manager=npm

####### SMOKE TEST STAGE #######
api test:
  stage: smoke test
  only:
    - dev
  dependencies:
    - :php
  tags:
    - 'gke'
  script:
    - smoke beta --config=4.8-elite --smoke-steps=copy:environment,copy:change-root,composer:install,test:api

acceptance test:
  stage: smoke test
  only:
    - dev
  dependencies:
    - :php
    - :build crm assets
  tags:
    - 'gke'
  script:
    - smoke beta --config=4.8-elite --smoke-steps=copy:environment,copy:change-root,composer:install,test:acceptance

e2e test:
  stage: smoke test
  only:
    - dev
  services:
    - selenium/standalone-chrome:3.4.0-chromium
  dependencies:
    - :php
  tags:
    - 'gke'
  script:
    - smoke beta --config=4.8-elite --smoke-steps=copy:environment,copy:change-root,composer:install,test:e2e
