-  repo: git://github.com/pre-commit/pre-commit-hooks
   sha: 'v0.9.2'
   hooks:
   -  id: check-merge-conflict
   -  id: no-commit-to-branch
      args: [-b dev]
   -  id: check-json
      exclude: tests/unit/Backend/Asset/fixtures/invalid.json
   -  id: check-yaml
   -  id: check-xml
-  repo: git://github.com/pre-commit/mirrors-eslint
   sha: 'v4.4.1'
   hooks:
   -  id: eslint
      files: \.jsx?$
      additional_dependencies:
      -  eslint@4.5.0
      -  babel-eslint@7.2.3
      -  eslint-plugin-react@7.3.0
-  repo: https://github.com/awebdeveloper/pre-commit-stylelint
   sha: '0.0.2'
   hooks:
   -  id: stylelint
      additional_dependencies:
      -  stylelint@8.0.0
      -  stylelint-config-standard@17.0.0
-  repo: https://github.com/digitalpulp/pre-commit-php.git
   sha: 1.3.0
   hooks:
   -  id: php-lint
   -  id: php-cs
      files: \.(php)$
      args: [-p]
#   -  id: php-cbf
#      files: \.(php)$
#      args: [-p]
#   -  id: php-cs-fixer
#      files: \.(php)$
#      args: [--level=PSR2]
