<?php

// IDX Compliance Settings
$_COMPLIANCE = array();

// Disclaimer Text
$_COMPLIANCE['disclaimer'] = array('');

if (in_array($_GET['load_page'], array('', 'search', 'search_map', 'details', 'map', 'streetview', 'birdseye', 'directions', 'local', 'brochure', 'sitemap', 'dashboard'))) {

	$_COMPLIANCE['disclaimer'][] = '<p class="disclaimer">'
	    .'NOTE: This representation is based in whole or in part on data generated by Kamloops and District Real Estate Association which assumes no responsibility for its accuracy.'
		.'</p>';
	$_COMPLIANCE['disclaimer'][] = '<p>'
	    .'<img alt="Kamloops img src District Real Estate Association Logo" src="'
		. Settings::getInstance()->SETTINGS['URL_IMG'] . 'logos/mlsrlogo.gif"'
		.' alt="KADREA Logo" border="0" style="height: 43px; margin-right: 2px;" />'
		.'</p>';
}

$_COMPLIANCE['details']['show_agent'] = true;
$_COMPLIANCE['details']['show_office'] = true;

$_COMPLIANCE['results']['show_office'] = true;
$_COMPLIANCE['results']['show_icon'] = '<img alt="Kamloops img src District Real Estate Association Logo" src="' . Settings::getInstance()->SETTINGS['URL_IMG']
	. 'logos/mlsrlogo.gif" border="0" style="height: 35px;" />';

$_COMPLIANCE['logo'] = Settings::getInstance()->SETTINGS['URL_IMG'] . 'logos/mlsrlogo.gif';
$_COMPLIANCE['logo_width'] = 35;   // Width (FPDF, Not Actual)
$_COMPLIANCE['logo_location'] = 1; // Placement
