modules:
  # Agent Subdomains - Requires Additional setup
  REW_AGENT_CMS: true
  # Agent Roster
  REW_AGENT_MANAGER: true
  # Agent Feature - Used on LECs
  REW_AGENT_SPOTLIGHT: true
  # Blog
  REW_BLOG_INSTALLED: true
  # Featured Listings
  REW_FEATURED_LISTINGS: true
  # Featured Listings Override
  REW_FEATURED_LISTINGS_OVERRIDE: false
  # Control Panel
  REW_IDX_CP: true
  # Quick Search
  REW_IDX_QUICKSEARCH: true
  # IDX Builder
  REW_IDX_BUILDER: true
  # Snippets
  REW_IDX_SNIPPETS: true
  # Map Search
  REW_IDX_MAPPING: true
  # Get Local / Onboard Infomatics / Demographics
  REW_IDX_ONBOARD: false
  # XML/HTML Sitemap
  REW_IDX_SITEMAP: true
  # Social Networking button / Share This!
  REW_IDX_SOCIAL_NETWORK: true
  # Google Streetview
  REW_IDX_STREETVIEW: true
  # Google Directions
  REW_IDX_DIRECTIONS: true
  # Bing BirdsEye
  REW_IDX_BIRDSEYE: true
  # 301 Redirect Tool
  REW_REWRITE_MANAGER: true
  # Slideshow Manager - Change slideshow images
  REW_SLIDESHOW_MANAGER: false
  # Testimonials
  REW_TESTIMONIALS: true
  # Featured Communities Tool
  REW_FEATURED_COMMUNITIES: true
  # Featured Offices for LECs
  REW_FEATURED_OFFICES: true
  # LEC 5 specific Feature Quick Search
  LEC5_FEATURE_SEARCH: false
  # Business Directory
  REW_DIRECTORY: false
  # REW Beacon Module (Online Leads)
  REW_BEACON: true
  # Conversion Tracking Tool
  REW_CONVERSION_TRACKING: true
  # IDX Meta Information
  REW_IDX_META_INFORMATION: true
  # IDX Price Change History
  REW_IDX_HISTORY_PRICE: true
  # IDX Status Change History
  REW_IDX_HISTORY_STATUS: true
  # REW Lenders Module (Lender Integration)
  REW_LENDERS_MODULE: true
  # REW ISA Module (Inside Sales Associates)
  REW_ISA_MODULE: true
  # REW Backend API
  REW_CRM_API: true
  # REW Backend API - Outgoing
  REW_CRM_API_OUTGOING: true
  # REW Partner Integration - Happy Grasshopper
  REW_PARTNERS_GRASSHOPPER: true
  # REW Partner Integration - BombBomb
  REW_PARTNERS_BOMBBOMB: true
  # REW Partner Integration - Follow Up Boss
  REW_PARTNERS_FOLLOWUPBOSS: true
  # REW Partner Integration - REW/Espresso Dialer ((int) - Number of active lines)
  REW_PARTNERS_ESPRESSO: 0
  # REW Partner Integration - WiseAgent
  REW_PARTNERS_WISEAGENT: false
  # REW Twilio Account SID
  REW_PARTNERS_TWILIO: false
  # REW Partner Integration - Zillow
  REW_PARTNERS_ZILLOW: true
  # REW Partner Integration - FirstCallAgent (FCA)
  REW_PARTNERS_FIRSTCALLAGENT: true
  # REW Partner Integration - Moxi CRM (string - ID of Moxi CRM Account (Referred to as 'agent_uuid' in their API docs))
  REW_PARTNERS_MOXI_CRM: false
  # Mail SMTP Provider - Mandrill
  REW_MAIL_MANDRILL: true
  # Mail SMTP Provider - SendGrid
  REW_MAIL_SENDGRID: true
  # REW Partner Integration - DotLoop
  REW_PARTNERS_DOTLOOP: true
  # Property Valuation Module
  REW_PROPERTY_VALUATION: false
  # New Home Builder Search (Additional Setup Required)
  REW_BUILDER: false
  # Google Calendar Push
  REW_GOOGLE_CALENDAR: false
  # Outlook Calendar Push
  REW_OUTLOOK_CALENDAR: false
  # Radio Landing Page Module (For R.A.T.E. Clients)
  REW_RADIO_LANDING_PAGE: false
  # SSO Integration With RE/MAX's Launchpad Software
  REW_REMAX_LAUNCHPAD: false
  # Showing Suite
  REW_SHOWING_SUITE: false
  # RT - Integration Module (Powered by RealtyTrac)
  REW_RT: false
  # RT - IDX Link Module (Powered by RealtyTrac)
  REW_RT_IDX: false
  # RT - Mapping Features (Auto-Disabled if Google Maps API Key Isn't Set Up)
  REW_RT_MAPPING: false
  # Action Plans
  REW_ACTION_PLANS: true
  # New Developments
  REW_DEVELOPMENTS: false
  # Agent Teams
  REW_TEAMS: true
  # Agent team Subdomains
  REW_TEAM_CMS: true
  # REW Zapier App Permission
  REW_ZAPIER_APP: false
  # CRM Shark Tank
  REW_SHARK_TANK: true
  # Saved Searches Responsive Template
  REW_SAVED_SEARCHES_RESPONSIVE: true
  # IDX Drive Time Search
  REW_IDX_DRIVE_TIME: false
  # ELM Immoviewer Implementation
  REW_IDX_IMMOVIEWER: true
  # REW Lite (single agent site)
  REW_LITE: false
